name: Build Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Build Windows executable
      run: GOOS=windows GOARCH=amd64 go build -o golang-winservice.exe ./cmd/service

    - name: Test
      run: go test -v ./...
